[package]
name = "kuverta-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "kuverta-desktop"
path = "src/main.rs"

[dependencies]
core-store.workspace = true
core-rpc.workspace = true
core-proto.workspace = true

tauri = "2.11.5"
tokio = { workspace = true, features = ["rt"] }
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[build-dependencies]
tauri-build = "2.6.3"
