[package]
name = "fuckmail-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "fuckmail"
path = "src/main.rs"

[dependencies]
core-store.workspace = true
core-proto.workspace = true
core-accounts.workspace = true

anyhow.workspace = true
clap.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
chrono.workspace = true
